datos = [
    "Una botella de plástico puede tardar cientos de años en degradarse.",
    "El aluminio puede reciclarse muchas veces sin perder calidad.",
    "Reciclar una lata de aluminio ahorra gran cantidad de energía.",
    "Los árboles absorben dióxido de carbono de la atmósfera.",
    "Una fuga de agua puede desperdiciar miles de litros al año.",
    "El papel reciclado reduce la necesidad de talar árboles.",
    "Los océanos producen gran parte del oxígeno que respiramos.",
    "Las bolsas plásticas pueden afectar a la vida marina.",
    "El vidrio es 100 porciento reciclable.",
    "Las abejas son esenciales para la polinización de muchos cultivos.",
    "Apagar una luz innecesaria ayuda a ahorrar energía.",
    "Los residuos orgánicos pueden convertirse en composta.",
    "El reciclaje ayuda a reducir la cantidad de basura en vertederos.",
    "La energía solar proviene del Sol y es renovable.",
    "Los bosques ayudan a regular el clima.",
    "El plástico es uno de los residuos más comunes en los océanos.",
    "Los árboles ayudan a reducir la temperatura en las ciudades.",
    "Una botella reutilizable puede reemplazar cientos de botellas desechables.",
    "La Tierra tiene más agua que tierra, pero poca es potable.",
    "El reciclaje de papel ahorra agua y energía.",
    "Las tortugas marinas pueden confundir plástico con alimento.",
    "El transporte público reduce emisiones por persona.",
    "Las energías renovables generan menos contaminación.",
    "La contaminación del aire afecta la salud humana.",
    "Las plantas ayudan a mejorar la calidad del aire.",
    "Una ducha corta puede ahorrar mucha agua.",
    "La reforestación ayuda a recuperar ecosistemas.",
    "Los focos LED consumen menos energía que los tradicionales.",
    "Reducir, reutilizar y reciclar son las tres R del cuidado ambiental.",
    "Los humedales ayudan a filtrar el agua naturalmente.",
    "Los residuos electrónicos requieren un manejo especial.",
    "Los corales son hogar de miles de especies marinas.",
    "Una bicicleta no produce emisiones contaminantes.",
    "El desperdicio de alimentos tiene impacto ambiental.",
    "La energía eólica utiliza la fuerza del viento.",
    "Muchos animales dependen de los bosques para sobrevivir.",
    "Las pilas no deben tirarse a la basura común.",
    "El compostaje reduce residuos orgánicos.",
    "Las áreas verdes urbanas ayudan a refrescar las ciudades.",
    "Los océanos absorben parte del CO₂ del planeta.",
    "El reciclaje crea oportunidades de empleo.",
    "El agua dulce representa una pequeña parte del agua del planeta.",
    "Los manglares protegen las costas de la erosión.",
    "La contaminación lumínica afecta a algunos animales.",
    "El uso responsable de energía ayuda al planeta.",
    "Las especies invasoras pueden alterar ecosistemas.",
    "Los árboles ayudan a prevenir la erosión del suelo.",
    "La biodiversidad fortalece los ecosistemas.",
    "Muchas aves migran miles de kilómetros cada año.",
    "El reciclaje reduce la extracción de materias primas.",
    "La Tierra tarda aproximadamente 365 días en dar una vuelta al Sol.",
    "Los bosques tropicales albergan gran biodiversidad.",
    "La contaminación acústica afecta a personas y animales.",
    "El agua es esencial para toda forma de vida conocida.",
    "Las energías limpias ayudan a combatir el cambio climático.",
    "Los parques urbanos benefician la salud de las personas.",
    "El cartón puede reciclarse varias veces.",
    "Las focas y tortugas pueden quedar atrapadas en residuos plásticos.",
    "La tala ilegal afecta a numerosos ecosistemas.",
    "Los árboles producen oxígeno durante la fotosíntesis.",
    "Las aves ayudan a dispersar semillas.",
    "Los residuos mal gestionados pueden contaminar ríos.",
    "La energía hidroeléctrica aprovecha el movimiento del agua.",
    "Los arrecifes de coral protegen las costas.",
    "Los paneles solares convierten luz solar en electricidad.",
    "El reciclaje ayuda a ahorrar espacio en vertederos.",
    "La desertificación afecta tierras fértiles.",
    "La contaminación del agua afecta a millones de seres vivos.",
    "Las selvas ayudan a regular el ciclo del agua.",
    "Las plantas capturan carbono atmosférico.",
    "La reutilización reduce la generación de residuos.",
    "El papel proviene principalmente de la madera.",
    "Las botellas de vidrio pueden reutilizarse muchas veces.",
    "La educación ambiental fomenta hábitos sostenibles.",
    "Los océanos cubren aproximadamente el 70% de la superficie terrestre.",
    "Las ballenas ayudan al equilibrio de los ecosistemas marinos.",
    "Los bosques almacenan grandes cantidades de carbono.",
    "Las energías renovables son recursos que se regeneran naturalmente.",
    "Los residuos orgánicos pueden convertirse en fertilizante natural.",
    "Las plantas interiores pueden mejorar el ambiente de una habitación.",
    "Las lluvias ayudan a recargar acuíferos.",
    "La sobrepesca puede afectar poblaciones marinas.",
    "Los glaciares almacenan gran cantidad de agua dulce.",
    "Las hojas caídas pueden utilizarse para composta.",
    "El consumo responsable reduce el impacto ambiental.",
    "Los árboles proporcionan sombra y refugio.",
    "Las bolsas reutilizables ayudan a reducir residuos.",
    "El reciclaje de vidrio ahorra materias primas.",
    "Las energías limpias reducen emisiones contaminantes.",
    "Los ecosistemas saludables benefician a las personas.",
    "Las semillas pueden viajar grandes distancias gracias al viento.",
    "La naturaleza proporciona recursos esenciales para la vida.",
    "La protección ambiental es una responsabilidad compartida.",
    "Los residuos reciclables tienen valor si se separan correctamente.",
    "Las áreas naturales protegidas ayudan a conservar especies.",
    "Pequeñas acciones sostenibles pueden generar grandes cambios.",
    "Cuidar el planeta beneficia a las generaciones futuras."
]
