
retos = [
    "Usa una botella reutilizable hoy",
    "Apaga las luces al salir de una habitación",
    "Recicla una botella de plástico",
    "Recicla una lata de aluminio",
    "Recoge 5 residuos del suelo",
    "Usa una bolsa reutilizable",
    "Desconecta un cargador que no uses",
    "Reduce tu tiempo de ducha en 2 minutos",
    "Reutiliza una hoja de papel",
    "Camina para un trayecto corto",
    "Usa menos agua al cepillarte los dientes",
    "Evita usar popotes hoy",
    "Apaga la televisión cuando no la veas",
    "Separa residuos orgánicos e inorgánicos",
    "Utiliza una taza reutilizable",
    "Evita imprimir documentos innecesarios",
    "Reutiliza un envase de vidrio",
    "Lleva tu propia botella al salir",
    "Recicla una caja de cartón",
    "Apaga tu computadora cuando termines",
    "Comparte un consejo ecológico",
    "Riega plantas con agua reutilizada",
    "Evita productos de un solo uso",
    "Usa luz natural durante una hora",
    "Limpia un área verde cercana",
    "Revisa fugas de agua en casa",
    "Recicla papel usado",
    "Reduce el uso del aire acondicionado",
    "Usa transporte público si es posible",
    "Recoge basura durante un paseo",
    "Apaga ventiladores vacíos",
    "Reutiliza una bolsa de plástico",
    "Planta una semilla",
    "Lava ropa con carga completa",
    "Cierra la llave mientras te enjabonas",
    "Comparte información sobre reciclaje",
    "Evita comprar productos con exceso de empaque",
    "Usa pilas recargables si puedes",
    "Limpia tu escritorio y recicla papel",
    "Dona algo que ya no uses",
    "Evita desperdiciar comida hoy",
    "Haz composta con residuos orgánicos",
    "Usa ambos lados de una hoja",
    "Reduce el brillo de tu monitor",
    "Desconecta aparatos en modo espera",
    "Recicla una revista vieja",
    "Recoge basura en tu escuela",
    "Usa jabón biodegradable",
    "Lleva comida en recipientes reutilizables",
    "Evita usar vasos desechables",
    "Ahorra agua al lavar platos",
    "Usa una bicicleta si es posible",
    "Comparte un dato ambiental",
    "Recicla envases de cartón",
    "Apaga luces innecesarias por 3 horas",
    "Reduce el uso de plástico hoy",
    "Reutiliza una caja",
    "Clasifica correctamente tus residuos",
    "Usa menos papel durante el día",
    "Limpia una zona de tu colonia",
    "Ayuda a alguien a reciclar",
    "Evita desperdiciar energía",
    "Apoya un negocio local sostenible",
    "Recoge 10 colillas de cigarro",
    "Usa menos servilletas",
    "Reduce tu consumo de agua",
    "Recicla un envase metálico",
    "Utiliza una mochila en vez de bolsas",
    "Apaga dispositivos que no uses",
    "Planta una flor",
    "Aprende algo nuevo sobre reciclaje",
    "Comparte un meme ecológico",
    "Evita usar productos desechables",
    "Usa una botella rellenable",
    "Limpia tu entorno inmediato",
    "Reduce el tiempo de uso del automóvil",
    "Compra productos reutilizables",
    "Ahorra energía durante una hora",
    "Reutiliza una libreta vieja",
    "Recicla un cuaderno usado",
    "Usa menos detergente",
    "Apaga luces durante el día",
    "Evita desperdiciar alimentos",
    "Lava frutas sin desperdiciar agua",
    "Recoge basura en un parque",
    "Utiliza focos LED",
    "Reduce el uso de papel aluminio",
    "Reutiliza recipientes plásticos",
    "Usa menos bolsas de plástico",
    "Repara algo en lugar de tirarlo",
    "Recicla un folleto viejo",
    "Dona ropa en buen estado",
    "Recoge residuos reciclables",
    "Evita compras innecesarias",
    "Usa transporte compartido",
    "Desconecta aparatos toda la noche",
    "Planta una planta pequeña",
    "Limpia una maceta",
    "Recicla empaques de cartón",
    "Ahorra agua durante el lavado",
    "Evita usar platos desechables",
    "Comparte un reto ecológico",
    "Usa menos energía en tu habitación",
    "Recicla una hoja de papel",
    "Recoge residuos electrónicos para reciclar",
    "Investiga un problema ambiental",
    "Utiliza menos plástico en tu comida",
    "Ahorra electricidad hoy",
    "Apaga una luz que olvidaste encendida",
    "Reduce tu consumo de refrescos embotellados",
    "Usa una cuchara reutilizable",
    "Recoge basura durante 10 minutos",
    "Limpia una banqueta",
    "Recicla una botella de vidrio",
    "Evita usar cubiertos desechables",
    "Usa menos agua caliente",
    "Comparte una noticia ambiental positiva",
    "Reutiliza papel para notas",
    "Usa una lonchera reutilizable",
    "Reduce el uso del automóvil por un día",
    "Recoge residuos en tu salón",
    "Ayuda a clasificar basura",
    "Reutiliza una botella",
    "Evita desperdiciar electricidad",
    "Usa una bolsa de tela",
    "Recicla un periódico",
    "Ahorra agua al lavar tus manos",
    "Apaga tu consola cuando termines",
    "Reduce el uso de empaques",
    "Recoge 15 residuos pequeños",
    "Investiga una especie en peligro",
    "Usa menos papel higiénico",
    "Comparte una acción ecológica",
    "Planta una semilla en algodón",
    "Limpia tu patio",
    "Evita imprimir hoy",
    "Recicla envases limpios",
    "Usa menos energía en dispositivos",
    "Desconecta aparatos por una hora",
    "Recoge residuos reciclables en casa",
    "Reduce tu generación de basura",
    "Usa una botella reutilizable todo el día",
    "Apaga las luces antes de dormir",
    "Recicla una caja de cereal",
    "Usa transporte ecológico",
    "Evita usar bolsas nuevas",
    "Comparte una foto de una planta",
    "Reutiliza un frasco de vidrio",
    "Ahorra agua al cocinar",
    "Recoge basura en una cancha",
    "Limpia una zona común",
    "Reduce el consumo de energía en casa",
    "Recicla envases de plástico",
    "Evita desperdiciar pan",
    "Usa una servilleta de tela",
    "Desconecta el microondas cuando no se use",
    "Apaga una luz innecesaria",
    "Aprende sobre energías renovables",
    "Recicla empaques de papel",
    "Usa menos plástico en compras",
    "Reutiliza materiales escolares",
    "Reduce el uso de papel por un día",
    "Recoge residuos cerca de tu casa",
    "Limpia un espacio verde",
    "Ahorra energía durante la tarde",
    "Recicla materiales limpios",
    "Utiliza agua responsablemente",
    "Evita productos sobreempaquetados",
    "Usa una botella de acero inoxidable",
    "Reutiliza una bolsa de regalo",
    "Apaga aparatos antes de salir",
    "Comparte un video educativo ambiental",
    "Recoge basura después de comer",
    "Ayuda a mantener limpio un espacio",
    "Recicla envases de comida",
    "Reduce residuos durante el día",
    "Usa una libreta hasta terminarla",
    "Reutiliza papel de borrador",
    "Apaga el monitor cuando descanses",
    "Evita usar plástico innecesario",
    "Comparte un consejo para ahorrar agua",
    "Limpia residuos de una jardinera",
    "Recoge basura durante 15 minutos",
    "Planta una nueva semilla",
    "Recicla papel de oficina",
    "Utiliza una bolsa reutilizable en compras",
    "Reduce el desperdicio de alimentos",
    "Usa menos electricidad por una tarde",
    "Apaga dispositivos antes de dormir",
    "Comparte una acción ecológica en Discord",
    "Ayuda a un familiar a reciclar",
    "Reduce el uso de desechables hoy",
    "Investiga cómo reciclar pilas",
    "Reutiliza un recipiente viejo",
    "Recoge 20 residuos pequeños",
    "Ahorra agua durante todo el día",
    "Usa transporte sostenible",
    "Comparte una idea para cuidar el planeta",
    "Recicla correctamente tus residuos de hoy"
]
