tips = [
    "Lleva siempre una botella reutilizable.",
    "Apaga las luces cuando salgas de una habitación.",
    "Usa bolsas reutilizables para tus compras.",
    "Reduce el tiempo de tus duchas.",
    "Desconecta cargadores que no estés usando.",
    "Recicla papel, plástico y vidrio correctamente.",
    "Utiliza focos LED para ahorrar energía.",
    "Aprovecha la luz natural durante el día.",
    "Evita imprimir documentos innecesarios.",
    "Reutiliza hojas por ambos lados.",
    "Camina o usa bicicleta en trayectos cortos.",
    "Comparte consejos ecológicos con tus amigos.",
    "Separa los residuos orgánicos de los inorgánicos.",
    "Evita productos de un solo uso.",
    "Usa recipientes reutilizables para tus alimentos.",
    "Compra solo lo que realmente necesitas.",
    "Lava la ropa con cargas completas.",
    "Riega las plantas temprano o al atardecer.",
    "Cierra la llave mientras te cepillas los dientes.",
    "Reutiliza frascos y envases de vidrio.",
    "Compra productos locales cuando sea posible.",
    "Evita desperdiciar comida.",
    "Dona ropa que ya no uses.",
    "Usa transporte público cuando puedas.",
    "Reduce el uso del aire acondicionado.",
    "Apaga la computadora al terminar de usarla.",
    "Mantén limpias las áreas verdes.",
    "Participa en jornadas de limpieza.",
    "Utiliza servilletas de tela.",
    "Lleva tu propia taza para bebidas.",
    "Recicla las cajas de cartón.",
    "Aprende sobre compostaje.",
    "Reduce el uso de plástico en tu día a día.",
    "Compra productos con menos empaques.",
    "Utiliza pilas recargables.",
    "Planta una semilla o una planta.",
    "Comparte información sobre reciclaje.",
    "Limpia los filtros de tus aparatos eléctricos.",
    "Ahorra agua al lavar platos.",
    "Repara objetos antes de desecharlos.",
    "Usa una lonchera reutilizable.",
    "Recoge basura si la encuentras en tu camino.",
    "Evita usar vasos desechables.",
    "Utiliza jabón biodegradable.",
    "Reduce el consumo de papel.",
    "Recicla periódicos y revistas.",
    "Apoya iniciativas ambientales locales.",
    "Lleva residuos electrónicos a centros de reciclaje.",
    "Evita tirar aceite por el drenaje.",
    "Usa menos productos empaquetados.",
    "Prefiere productos reutilizables.",
    "Comparte memes ecológicos con conciencia.",
    "Mantén una planta en tu habitación.",
    "Evita el desperdicio de energía.",
    "Reduce el brillo de tu pantalla.",
    "Usa agua responsablemente al cocinar.",
    "Compra artículos duraderos.",
    "Recicla botellas de plástico.",
    "Utiliza cubiertos reutilizables.",
    "Recoge residuos durante tus paseos.",
    "Evita dejar aparatos en modo espera.",
    "Usa menos bolsas de plástico.",
    "Lleva siempre una bolsa de tela.",
    "Cuida las áreas naturales que visites.",
    "No arrojes basura en calles o parques.",
    "Utiliza menos detergente al lavar ropa.",
    "Comparte un dato ecológico cada semana.",
    "Reduce el desperdicio de alimentos.",
    "Evita quemar basura.",
    "Recicla latas de aluminio.",
    "Usa botellas rellenables.",
    "Reduce el uso de papel aluminio.",
    "Prefiere envases retornables.",
    "Utiliza energías renovables cuando sea posible.",
    "Mantén cerradas puertas y ventanas con aire acondicionado.",
    "Apaga ventiladores cuando no haya nadie.",
    "Recicla envases de vidrio.",
    "Evita comprar por impulso.",
    "Limpia una zona común de tu comunidad.",
    "Utiliza productos ecológicos.",
    "Lava frutas y verduras sin desperdiciar agua.",
    "Recicla cuadernos usados.",
    "Reduce el uso de agua caliente.",
    "Usa la bicicleta para trayectos cortos.",
    "Evita los popotes desechables.",
    "Participa en campañas de reforestación.",
    "Ayuda a otros a aprender sobre reciclaje.",
    "Comparte tus hábitos ecológicos.",
    "Reduce el consumo de energía en casa.",
    "Mantén limpio tu entorno.",
    "Compra ropa de calidad que dure más.",
    "Reutiliza materiales escolares.",
    "Aprovecha al máximo los alimentos.",
    "Utiliza termos para bebidas.",
    "Investiga sobre especies en peligro de extinción.",
    "Consume de forma responsable.",
    "Apaga luces innecesarias durante el día.",
    "Recicla siempre que sea posible.",
    "Pequeñas acciones diarias generan grandes cambios."
]
